### ISSUE TITLE
More modules

### ISSUE THREAD

**Issue by blaisek** [eturbat4312/ft_transendence#40]
With the chat, we will have 5 modules. We need 2 more major modules or 1 Major Module and 2 minor modules to get 100%
like for exemple : 
- add new game (Major module)
- Implement an IA (Major module)
- add personalization options (minor module)
- Dashboards with statistics (minor module)

**Comment by blaisek** [comment]
- Expanding Browser Compatibility. (minor module)
- Support on all devices (minor module)
- Implement Two-Factor Authentication (2FA) and JWT (major module)

**Comment by eturbat4312** [comment]
Premetheus & grafana (minor module)

**Comment by porgito** [comment]
add New Game -> Historique des jeux pour le tic tac toes
