### ISSUE TITLE
Create Django API

### ISSUE THREAD

**Issue by blaisek** [eturbat4312/ft_transendence#9]
we need  an API  with Django REST Framework to manage the registrations, and invitations, configure games, scores, and statistics, and communicate with the database

**Comment by VidyaYadavv1519** [comment]
Hiiiii, Can you please assign me this issue ??

**Comment by blaisek** [comment]
@VidyaYadavv1519 No, but if you want to propose something, you can still make a PR.

**Comment by VidyaYadavv1519** [comment]
no problem
